{{- if .Values.provisioning.backends }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logicle.fullname" . }}-backends
  labels:
    {{- include "logicle.labels" . | nindent 4 }}
data:
  00-backends.yaml: |
{{ .Values.provisioning.backends | indent 4 }}
{{- end }}
