apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logicle.fullname" . }}
  labels:
    {{- include "logicle.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.config.NEXTAUTH_SECRET | quote }}
  DATABASE_URL: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.dbName }}"
  LOGICLECLOUD_API_KEY: "{{ .Values.logiclecloud.llmproxy_api_key }}"
  LOGICLECLOUD_TOOLS_API_KEY: "{{ .Values.logiclecloud.tools_api_key }}"
  EXA_API_KEY: "{{ .Values.tools.exa_api_key }}"
  IMAGEGEN_OPENAI_API_KEY: "{{ .Values.imagegen.openai_api_key }}"
  IMAGEGEN_TOGETHER_API_KEY: "{{ .Values.imagegen.together_api_key }}"
  IMAGEGEN_REPLICATE_API_KEY: "{{ .Values.imagegen.replicate_api_key }}"
  IMAGEGEN_GEMINI_API_KEY: "{{ .Values.imagegen.gemini_api_key }}"
  AUDIO_TRANSCRIPTION_ASSEMBLYAI_API_KEY: "{{ .Values.audio_transcription.assemblyai_api_key }}"
{{- if eq .Values.storage.type "s3" }}
  AWS_ACCESS_KEY_ID: "{{ .Values.storage.s3.access_key_id }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.storage.s3.secret_access_key }}"
  AWS_DEFAULT_REGION: "{{ .Values.storage.s3.default_region }}"
{{- end }}
