apiVersion: v1
kind: Service
metadata:
  name: {{ include "logicle.fullname" . }}
  labels:
    {{- include "logicle.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "logicle.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
