import { defineConfig } from 'vitest/config'
import path from 'node:path'

const exactAlias = (find: string, replacement: string) => ({
  find: new RegExp(`^${find.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`),
  replacement: path.resolve(__dirname, replacement),
})

const prefixAlias = (find: string, replacement: string) => ({
  find: new RegExp(`^${find.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(\\/.*)?$`),
  replacement: `${path.resolve(__dirname, replacement)}$1`,
})

export default defineConfig({
  test: {
    environment: 'node',
    include: ['**/__tests__/**/*.{test,spec}.ts', '**/__tests__/**/*.ts'],
    env: {
      APP_URL: 'http://localhost:3000',
      DATABASE_URL: 'memory:',
      FILE_STORAGE_LOCATION: '.',
    },
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov', 'html'],
      include: ['packages/core/src/**', 'apps/backend/lib/**'],
      exclude: ['apps/backend/lib/vendor/**'],
    },
  },
  resolve: {
    alias: [
      exactAlias('@/lib/fetch', 'apps/frontend/lib/fetch/index.ts'),
      prefixAlias('@/lib/fetch', 'apps/frontend/lib/fetch'),
      exactAlias('@/lib/savefile', 'apps/frontend/lib/savefile.ts'),
      exactAlias('@/lib/resizeImage', 'apps/frontend/lib/resizeImage.ts'),
      exactAlias('@/lib/dnd', 'apps/frontend/lib/dnd.ts'),
      exactAlias('@/lib/codeblock', 'apps/frontend/lib/codeblock.ts'),
      exactAlias('@/lib/version', 'apps/frontend/lib/version.ts'),
      prefixAlias('@/frontend', 'apps/frontend'),
      exactAlias('@/lib/mimeTypes', 'apps/frontend/lib/mimeTypes.ts'),
      exactAlias('@/lib/const', 'apps/frontend/lib/const.ts'),
      exactAlias('@/lib/logging', 'apps/backend/lib/logging.ts'),
      exactAlias('@/lib/routes', 'apps/backend/lib/routes.ts'),
      exactAlias('@/lib/auth', 'apps/backend/lib/auth.ts'),
      prefixAlias('@/lib/auth', 'apps/backend/lib/auth'),
      exactAlias('@/lib/models', 'apps/backend/lib/models.ts'),
      exactAlias('@/lib/parameters', 'apps/backend/lib/parameters.ts'),
      exactAlias('@/lib/properties', 'apps/backend/lib/properties.ts'),
      exactAlias('@/lib/provision', 'apps/backend/lib/provision.ts'),
      exactAlias('@/lib/provision_schema', 'apps/backend/lib/provision_schema.ts'),
      exactAlias('@/lib/uris', 'apps/backend/lib/uris.ts'),
      exactAlias('@/lib/fileAnalysis', 'apps/backend/lib/fileAnalysis.ts'),
      exactAlias('@/lib/file-analysis-runtime', 'apps/backend/lib/file-analysis-runtime.ts'),
      exactAlias('@/lib/fileAnalysisPayload', 'apps/backend/lib/fileAnalysisPayload.ts'),
      exactAlias('@/lib/MessageAuditor', 'apps/backend/lib/MessageAuditor.ts'),
      exactAlias('@/lib/satelliteHub', 'apps/backend/lib/satelliteHub.ts'),
      exactAlias('@/lib/satelliteTypes', 'apps/backend/lib/satelliteTypes.ts'),
      exactAlias('@/lib/userSecrets', 'apps/backend/lib/userSecrets.ts'),
      exactAlias('@/lib/chat/litellm', 'apps/backend/lib/chat/litellm/index.ts'),
      prefixAlias('@/lib/chat/litellm', 'apps/backend/lib/chat/litellm'),
      exactAlias('@/lib/chat/models', 'packages/core/src/models/index.ts'),
      prefixAlias('@/lib/chat/models', 'packages/core/src/models'),
      exactAlias('@/lib/storage', 'apps/backend/lib/storage/index.ts'),
      prefixAlias('@/lib/storage', 'apps/backend/lib/storage'),
      exactAlias('@/lib/textextraction', 'apps/backend/lib/textextraction/index.ts'),
      prefixAlias('@/lib/textextraction', 'apps/backend/lib/textextraction'),
      prefixAlias('@/lib/vendor', 'apps/backend/lib/vendor'),
      prefixAlias('@/lib/http', 'apps/backend/lib/http'),
      prefixAlias('@/lib/tracing', 'apps/backend/lib/tracing'),
      prefixAlias('@/lib/bootstrap', 'apps/backend/lib/bootstrap'),
      prefixAlias('@/lib/backend', 'apps/backend/lib/backend'),
      prefixAlias('@/lib', 'packages/core/src'),
      prefixAlias('@/models', 'apps/backend/models'),
      prefixAlias('@/db', 'apps/backend/db'),
      prefixAlias('@/types', 'packages/core/src/types'),
      prefixAlias('@/components', 'apps/frontend/components'),
      prefixAlias('@/services', 'apps/frontend/services'),
      prefixAlias('@/hooks', 'apps/frontend/hooks'),
      prefixAlias('@/pages', 'apps/frontend/pages'),
      prefixAlias('@/app/api', 'apps/backend/api'),
      prefixAlias('@/app', 'apps/frontend/app'),
      prefixAlias('@/api', 'apps/backend/api'),
      prefixAlias('@/backend', 'apps/backend'),
      prefixAlias('@/ee', 'apps/backend/ee'),
      exactAlias('lib/storage', 'apps/backend/lib/storage/index.ts'),
      prefixAlias('lib/storage', 'apps/backend/lib/storage'),
      exactAlias('lib/textextraction', 'apps/backend/lib/textextraction/index.ts'),
      prefixAlias('lib/textextraction', 'apps/backend/lib/textextraction'),
      exactAlias('lib/uris', 'apps/backend/lib/uris.ts'),
      exactAlias('lib/chat/models', 'packages/core/src/models/index.ts'),
      prefixAlias('lib/chat/models', 'packages/core/src/models'),
      prefixAlias('lib/vendor', 'apps/backend/lib/vendor'),
      prefixAlias('lib/http', 'apps/backend/lib/http'),
      prefixAlias('lib/tracing', 'apps/backend/lib/tracing'),
      prefixAlias('lib/bootstrap', 'apps/backend/lib/bootstrap'),
      prefixAlias('lib/backend', 'apps/backend/lib/backend'),
      prefixAlias('frontend', 'apps/frontend'),
      prefixAlias('lib', 'packages/core/src'),
      prefixAlias('models', 'apps/backend/models'),
      prefixAlias('db', 'apps/backend/db'),
      prefixAlias('types', 'packages/core/src/types'),
      prefixAlias('components', 'apps/frontend/components'),
      prefixAlias('services', 'apps/frontend/services'),
      prefixAlias('hooks', 'apps/frontend/hooks'),
      prefixAlias('pages', 'apps/frontend/pages'),
      prefixAlias('app', 'apps/frontend/app'),
      prefixAlias('backend', 'apps/backend'),
      prefixAlias('ee', 'apps/backend/ee'),
      exactAlias('templates', 'apps/backend/lib/templates.ts'),
      exactAlias('@logicle/file-analyzer/analyzers', 'packages/file-analyzer/src/analyzers.ts'),
      exactAlias('@logicle/file-analyzer/worker', 'packages/file-analyzer/src/worker/runtime.ts'),
      exactAlias('@logicle/file-analyzer', 'packages/file-analyzer/src/index.ts'),
      { find: '@', replacement: path.resolve(__dirname) },
    ],
  },
})
