version: '3'
services:
  app:
    image: ghcr.io/logicleai/logicle:latest
    restart: always
    environment:
      PORT: 80
      APP_URL: http://$APP_PUBLIC_FQDN
      DB_ENGINE: ${DB_ENGINE}
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: http://$APP_PUBLIC_FQDN/api/auth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    ports:
      - 80:80
    volumes:
      - sqlite-data:/data/sqlite
      - uploaded-files-data:/data/files

volumes:
  sqlite-data:
  uploaded-files-data: