name: "🐛 Bug Report"
description: "Submit a bug report"
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Your contribution is greatly appreciated! Please fill out this form to submit your feature request. 🙏
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "📜 Issue Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "It bugs out when ..."
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: "👟 Steps to Reproduce"
      description: "Please provide the steps to reproduce the bug."
      placeholder: "1. Navigate to '...'
                    2. Click on '....'
                    3. Scroll to '....'
                    4. Observe the error"
  - type: textarea
    id: current-behavior
    validations:
      required: true
    attributes:
      label: "👎 Current Behavior with Screenshots"
      description: "Describe what happens instead of the expected behavior. Include screenshots if possible."
      placeholder: "Currently, ..."
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: "👍 Expected Behavior"
      description: "Explain what you expected to happen."
      placeholder: "Expected behavior is ..."
  - type: textarea
    id: additional-context
    validations:
      required: false
    attributes:
      label: "📃 Additional Context"
      description: "Provide any additional information that might be helpful."
      placeholder: "Additional details ..."
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: "🏢 Code of Conduct Acknowledgement"
      options:
        - label: "I have read the [Contributing Guidelines](https://github.com/logicleai/logicle/blob/main/CONTRIBUTING.md)"
          required: true