#!/usr/bin/env tsx
import fs from 'node:fs/promises'
import path from 'node:path'

const projectRoot = process.cwd()
const migrationsDir = path.join(projectRoot, 'apps', 'backend', 'db', 'migrations')
const outputFile = path.join(projectRoot, 'apps', 'backend', 'db', 'migrations.generated.ts')

const toIdentifier = (name: string) => {
  const normalized = name.replace(/[^a-zA-Z0-9]+(.)/g, (_, char: string) => char.toUpperCase())
  return `m${normalized.replace(/[^a-zA-Z0-9]/g, '_')}`
}

async function main() {
  const entries = (await fs.readdir(migrationsDir))
    .filter((entry) => entry.endsWith('.ts'))
    .sort()
    .map((entry) => entry.replace(/\.ts$/, ''))

  const importLines = entries.map((entry) => {
    return `import * as ${toIdentifier(entry)} from './migrations/${entry}'`
  })

  const manifestLines = entries.map((entry) => {
    return `  '${entry}': ${toIdentifier(entry)},`
  })

  const file = [
    '// This file is generated by scripts/generate-migration-manifest.ts',
    '// Do not edit it by hand.',
    ...importLines,
    '',
    "import type { MigrationWithDialect } from './migrations'",
    '',
    'export const migrationModules: Record<string, MigrationWithDialect> = {',
    ...manifestLines,
    '}',
    '',
  ].join('\n')

  await fs.writeFile(outputFile, file)
}

await main()
