#!/usr/bin/env tsx
import fs from 'node:fs/promises'
import path from 'node:path'

const projectRoot = process.cwd()
const apiRoot = path.join(projectRoot, 'apps', 'backend', 'api')
const outputFile = path.join(projectRoot, 'packages', 'core', 'src', 'lib', 'backend', 'routes.generated.ts')

async function findRouteFiles(dir: string): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true })
  const files: string[] = []

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...(await findRouteFiles(fullPath)))
      continue
    }
    if (entry.isFile() && /^route\.tsx?$/.test(entry.name)) {
      files.push(fullPath)
    }
  }

  return files
}

const toPathname = (filePath: string) => {
  const relativeDir = path.relative(apiRoot, path.dirname(filePath))
  const routePath = relativeDir.split(path.sep).filter(Boolean).join('/')
  return routePath ? `/api/${routePath}` : '/api'
}

const toImportPath = (filePath: string) => {
  const relativePath = path.relative(projectRoot, filePath).replace(/\\/g, '/')
  return `@/${relativePath.replace(/^apps\/backend\//, 'backend/').replace(/\.(ts|tsx)$/, '')}`
}

async function main() {
  const routeFiles = (await findRouteFiles(apiRoot)).sort()
  const lines = routeFiles.map((filePath) => {
    return `  { pathname: '${toPathname(filePath)}', load: () => import('${toImportPath(filePath)}') },`
  })

  const file = [
    '// This file is generated by scripts/generate-backend-route-manifest.ts',
    '// Do not edit it by hand.',
    '',
    'export const backendRouteModules = [',
    ...lines,
    '] as const',
    '',
  ].join('\n')

  await fs.writeFile(outputFile, file)
}

await main()
