import { LlmModel } from '.'
import {
  claude35HaikuModel,
  claude35SonnetModel,
  claude37SonnetModel,
  claude3HaikuModel,
  claude3OpusModel,
  claude3SonnetModel,
  claude41OpusModel,
  claude45HaikuModel,
  claude45OpusModel,
  claude45SonnetModel,
  claude46SonnetModel,
  claude4OpusModel,
  claude4SonnetModel,
  claude5SonnetModel,
  claudeSonnetLatest,
} from './anthropic'
import {
  gpt4oMiniModel,
  gpt4oModel,
  gpt35Model,
  o1MiniModel,
  o1Model,
  o3MiniModel,
  o4MiniModel,
  gpt41Model,
  o3Model,
  gpt41MiniModel,
  gpt5MiniModel,
  gpt5Model,
  o4MiniDeepResearchModel,
  o3DeepResearchModel,
  gptLatest,
  gpt51Model,
  gpt5ChatModel,
  gpt52Model,
  gpt54Model,
} from './openai'
import { perplexityModels } from './perplexity'
import {
  gemini15FlashModel,
  gemini15ProModel,
  gemini20FlashLiteModel,
  gemini20FlashModel,
  gemini20ProModel,
  gemini25ProModel,
  gemini25FlashModel,
  geminiProLatest,
  gemini30ProModel,
  gemini31FlashLite,
  gemini31ProModel,
  gemini35FlashModel,
} from './vertex'

export const logicleModels: LlmModel[] = [
  { ...gptLatest, id: 'gpt-5-latest' },
  gpt35Model,
  gpt4oModel,
  gpt4oMiniModel,
  gpt41Model,
  gpt41MiniModel,
  gpt5Model,
  gpt5MiniModel,
  gpt51Model,
  gpt52Model,
  gpt54Model,
  { ...gpt5ChatModel, id: 'chatgpt-5-latest', name: 'GPT 5 Chat', model: 'chatgpt-5-latest' },
  o1Model,
  o1MiniModel,
  o3Model,
  o3DeepResearchModel,
  o3MiniModel,
  o4MiniModel,
  o4MiniDeepResearchModel,
  claude3SonnetModel,
  claude3HaikuModel,
  claude35SonnetModel,
  claude35HaikuModel,
  claude3OpusModel,
  claude37SonnetModel,
  claude4SonnetModel,
  claude4OpusModel,
  claude41OpusModel,
  claude45HaikuModel,
  claude45SonnetModel,
  claude46SonnetModel,
  claude45OpusModel,
  claude5SonnetModel,
  claudeSonnetLatest,
  gemini15ProModel,
  gemini15FlashModel,
  gemini20ProModel,
  gemini20FlashModel,
  gemini20FlashLiteModel,
  gemini25ProModel,
  gemini25FlashModel,
  gemini30ProModel,
  geminiProLatest,
  gemini31FlashLite,
  gemini31ProModel,
  gemini35FlashModel,
  ...perplexityModels,
].map((model) => {
  return {
    ...model,
    provider: 'logiclecloud',
  }
})
