import { EnrichedModel } from '.'

export const anthropicModels: EnrichedModel[] = [
  {
    name: 'Claude 3.5 Sonnet',
    description: 'Most intelligent model yet',
    id: 'claude-3-5-sonnet-20240620',
    object: 'model',
    created: 1698959748,
    owned_by: 'anthropic',
    context_length: 200000,
    tokenizer: 'anthropic',
    capabilities: {
      vision: true,
      function_calling: true,
    },
    prices: {
      input: 3,
      output: 15,
    },
  },
  {
    name: 'Claude 3 Opus',
    description: 'Powerful model for highly complex tasks',
    id: 'claude-3-opus-20240229',
    object: 'model',
    created: 1698959748,
    owned_by: 'anthropic',
    context_length: 200000,
    tokenizer: 'anthropic',
    capabilities: {
      vision: true,
      function_calling: true,
    },
    prices: {
      input: 15,
      output: 75,
    },
  },
  {
    name: 'Claude 3 Sonnet',
    description: 'Balance of intelligence and speed',
    id: 'claude-3-sonnet-20240229',
    object: 'model',
    created: 1698959748,
    owned_by: 'anthropic',
    context_length: 200000,
    tokenizer: 'anthropic',
    capabilities: {
      vision: true,
      function_calling: true,
    },
    prices: {
      input: 3,
      output: 15,
    },
  },
  {
    name: 'Claude 3 Haiku',
    description: 'Fastest and most compact model for near-instant responsiveness',
    id: 'claude-3-haiku-20240307',
    object: 'model',
    created: 1698959748,
    owned_by: 'anthropic',
    context_length: 200000,
    tokenizer: 'anthropic',
    capabilities: {
      vision: true,
      function_calling: true,
    },
    prices: {
      input: 0.25,
      output: 1.25,
    },
  },
  {
    name: 'Claude 2.1',
    description: 'Updated version of Claude 2 with improved accuracy',
    id: 'claude-2.1',
    object: 'model',
    created: 1698959748,
    owned_by: 'anthropic',
    context_length: 200000,
    tokenizer: 'anthropic',
    capabilities: {
      vision: false,
      function_calling: false,
    },
    prices: {
      input: 8,
      output: 24,
    },
  },
  {
    name: 'Claude 2',
    description: 'Predecessor to Claude 3, offering strong all-round performance',
    id: 'claude-2.0',
    object: 'model',
    created: 1698959748,
    owned_by: 'anthropic',
    context_length: 100000,
    tokenizer: 'anthropic',
    capabilities: {
      vision: false,
      function_calling: false,
    },
    prices: {
      input: 8,
      output: 24,
    },
  },
  {
    name: 'Claude Instant 1.2',
    description: 'Our cheapest small and fast model, a predecessor of Claude Haiku.',
    id: 'claude-instant-1.2',
    object: 'model',
    created: 1698959748,
    owned_by: 'anthropic',
    context_length: 100000,
    tokenizer: 'anthropic',
    capabilities: {
      vision: false,
      function_calling: false,
    },
    prices: {
      input: 0.8,
      output: 2.4,
    },
  },
]
