// This file is generated by scripts/generate-migration-manifest.ts
// Do not edit it by hand.
import * as m20240325Initialschema from './migrations/20240325-initialschema'
import * as m20240325Jackson from './migrations/20240325-jackson'
import * as m20240404Workspaces from './migrations/20240404-workspaces'
import * as m20240531Messageaudit from './migrations/20240531-messageaudit'
import * as m20240603Images from './migrations/20240603-images'
import * as m20240624AssistantTimestamps from './migrations/20240624-assistant_timestamps'
import * as m20240804AssistantTags from './migrations/20240804-assistant_tags'
import * as m20240904AssistantPrompts from './migrations/20240904-assistant_prompts'
import * as m20240930GenericBackendConfig from './migrations/20240930-generic_backend_config'
import * as m20241118BackendToolProvisioning from './migrations/20241118-backend_tool_provisioning'
import * as m20241119UserroleDbenum from './migrations/20241119-userrole_dbenum'
import * as m20241123ApikeysAndUserprovision from './migrations/20241123-apikeys_and_userprovision'
import * as m20241209AssistantProvisioning from './migrations/20241209-assistant_provisioning'
import * as m20241210FileEncryption from './migrations/20241210-file_encryption'
import * as m20241211UserPreferences from './migrations/20241211-user_preferences'
import * as m20250212LowercaseEmail from './migrations/20250212-lowercase_email'
import * as m20250215IdAssistantsharing from './migrations/20250215-id_assistantsharing'
import * as m20250216ConversationIndexes from './migrations/20250216-conversation_indexes'
import * as m20250217AssistantStatus from './migrations/20250217-assistant_status'
import * as m20250218ChatSharing from './migrations/20250218-chat_sharing'
import * as m20250322ToolPurpose from './migrations/20250322-tool_purpose'
import * as m20250324AssistantReasoning from './migrations/20250324-assistant_reasoning'
import * as m20250407UserSsoFlag from './migrations/20250407-user_sso_flag'
import * as m20250515AssistantVersions from './migrations/20250515-assistant_versions'
import * as m20250516ToolNewFields from './migrations/20250516-tool_new_fields'
import * as m20250718ToolSharing from './migrations/20250718-tool_sharing'
import * as m20251122UserProperties from './migrations/20251122-user_properties'
import * as m20251209Sso from './migrations/20251209-sso'
import * as m20260109DbBackedSessions from './migrations/20260109-db_backed_sessions'
import * as m20260112MessageVersion from './migrations/20260112-message_version'
import * as m20260129UserSecrets from './migrations/20260129-user_secrets'
import * as m20260202ToolSecrets from './migrations/20260202-tool_secrets'
import * as m20260312FileAnalysis from './migrations/20260312-file_analysis'
import * as m20260319MessageFeedback from './migrations/20260319-message_feedback'
import * as m20260320AssistantSubAssistants from './migrations/20260320-assistant_sub_assistants'

import type { MigrationWithDialect } from './migrations'

export const migrationModules: Record<string, MigrationWithDialect> = {
  '20240325-initialschema': m20240325Initialschema,
  '20240325-jackson': m20240325Jackson,
  '20240404-workspaces': m20240404Workspaces,
  '20240531-messageaudit': m20240531Messageaudit,
  '20240603-images': m20240603Images,
  '20240624-assistant_timestamps': m20240624AssistantTimestamps,
  '20240804-assistant_tags': m20240804AssistantTags,
  '20240904-assistant_prompts': m20240904AssistantPrompts,
  '20240930-generic_backend_config': m20240930GenericBackendConfig,
  '20241118-backend_tool_provisioning': m20241118BackendToolProvisioning,
  '20241119-userrole_dbenum': m20241119UserroleDbenum,
  '20241123-apikeys_and_userprovision': m20241123ApikeysAndUserprovision,
  '20241209-assistant_provisioning': m20241209AssistantProvisioning,
  '20241210-file_encryption': m20241210FileEncryption,
  '20241211-user_preferences': m20241211UserPreferences,
  '20250212-lowercase_email': m20250212LowercaseEmail,
  '20250215-id_assistantsharing': m20250215IdAssistantsharing,
  '20250216-conversation_indexes': m20250216ConversationIndexes,
  '20250217-assistant_status': m20250217AssistantStatus,
  '20250218-chat_sharing': m20250218ChatSharing,
  '20250322-tool_purpose': m20250322ToolPurpose,
  '20250324-assistant_reasoning': m20250324AssistantReasoning,
  '20250407-user_sso_flag': m20250407UserSsoFlag,
  '20250515-assistant_versions': m20250515AssistantVersions,
  '20250516-tool_new_fields': m20250516ToolNewFields,
  '20250718-tool_sharing': m20250718ToolSharing,
  '20251122-user_properties': m20251122UserProperties,
  '20251209-sso': m20251209Sso,
  '20260109-db_backed_sessions': m20260109DbBackedSessions,
  '20260112-message_version': m20260112MessageVersion,
  '20260129-user_secrets': m20260129UserSecrets,
  '20260202-tool_secrets': m20260202ToolSecrets,
  '20260312-file_analysis': m20260312FileAnalysis,
  '20260319-message_feedback': m20260319MessageFeedback,
  '20260320-assistant_sub_assistants': m20260320AssistantSubAssistants,
}
