import { LlmModel } from '.'
import {
  claude35HaikuModel,
  claude35SonnetModel,
  claude37SonnetModel,
  claude3HaikuModel,
  claude3OpusModel,
  claude3SonnetModel,
  claude41OpusModel,
  claude45HaikuModel,
  claude45OpusModel,
  claude45SonnetModel,
  claude4OpusModel,
  claude4SonnetModel,
  claudeSonnetLatest,
} from './anthropic'
import {
  gpt4oMiniModel,
  gpt4oModel,
  gpt35Model,
  o1MiniModel,
  o1Model,
  o3MiniModel,
  o4MiniModel,
  gpt41Model,
  o3Model,
  gpt41MiniModel,
  gpt5MiniModel,
  gpt5Model,
  o4MiniDeepResearchModel,
  o3DeepResearchModel,
  gptLatest,
  gpt51Model,
  gpt5ChatModel,
} from './openai'
import { perplexityModels } from './perplexity'
import {
  gemini15FlashModel,
  gemini15ProModel,
  gemini20FlashLiteModel,
  gemini20FlashModel,
  gemini20ProModel,
  gemini25ProModel,
  gemini25FlashModel,
  geminiProLatest,
  gemini30ProModel,
} from './vertex'

export const logicleModels: LlmModel[] = [
  gptLatest,
  gpt35Model,
  gpt4oModel,
  gpt4oMiniModel,
  gpt41Model,
  gpt41MiniModel,
  gpt5Model,
  gpt5MiniModel,
  gpt51Model,
  { ...gpt5ChatModel, id: 'chatgpt-5-latest', name: 'GPT 5 Chat', model: 'chatgpt-5-latest' },
  o1Model,
  o1MiniModel,
  o3Model,
  o3DeepResearchModel,
  o3MiniModel,
  o4MiniModel,
  o4MiniDeepResearchModel,
  { ...claude35SonnetModel, id: 'claude-3-5-sonnet', model: 'claude-3-5-sonnet' },
  { ...claude35HaikuModel, id: 'claude-3-5-haiku', model: 'claude-3-5-haiku' },
  { ...claude3OpusModel, id: 'claude-3-opus', model: 'claude-3-opus' },
  { ...claude37SonnetModel, id: 'claude-3-7-sonnet', model: 'claude-3-7-sonnet' },
  { ...claude4SonnetModel, id: 'claude-sonnet-4', model: 'claude-sonnet-4' },
  { ...claude4OpusModel, id: 'claude-opus-4', model: 'claude-opus-4' },
  { ...claude41OpusModel, id: 'claude-opus-4-1', model: 'claude-opus-4-1' },
  claude45HaikuModel,
  claude45SonnetModel,
  claude45OpusModel,
  claude3SonnetModel,
  claude3HaikuModel,
  claudeSonnetLatest,
  gemini15ProModel,
  gemini15FlashModel,
  gemini20ProModel,
  gemini20FlashModel,
  gemini20FlashLiteModel,
  gemini25ProModel,
  gemini25FlashModel,
  { ...gemini30ProModel, model: 'gemini-3.0-pro' },
  { ...geminiProLatest, model: 'gemini-3.0-pro' },
  ...perplexityModels,
].map((model) => {
  return {
    ...model,
    provider: 'logiclecloud',
  }
})
