version: "3"
services:
  app:
    image: ghcr.io/logicleai/logicle:v0.10.1
    restart: always
    environment:
      PORT: 8080
      APP_URL: https://$APP_PUBLIC_FQDN
      DB_ENGINE: ${DB_ENGINE}
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: https://$APP_PUBLIC_FQDN/api/auth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    volumes:
      - uploaded-files-data:/data/files
    networks:
      - logicle-network

  postgres-db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - logicle-network

  caddy:
    image: caddy:2
    restart: always
    command: caddy reverse-proxy --from https://${APP_PUBLIC_FQDN}:443 --to http://app:8080
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - logicle-network

volumes:
  uploaded-files-data:
  postgres-data:
  caddy_data:
  caddy_config:

networks:
  logicle-network:
