version: "3"
services:
  app:
    image: ghcr.io/logicleai/logicle:v0.8.1
    restart: always
    environment:
      PORT: 80
      APP_URL: http://$APP_PUBLIC_FQDN
      DB_ENGINE: ${DB_ENGINE}
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: http://$APP_PUBLIC_FQDN/api/auth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    ports:
      - 80:80
    volumes:
      - uploaded-files-data:/data/files
    networks:
      - logicle-network

  postgres-db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - logicle-network

volumes:
  uploaded-files-data:
  postgres-data:

networks:
  logicle-network:
