version: '3'
services:
  app:
    image: ghcr.io/logicleai/logicle:v0.2.1
    restart: always
    environment:
      PORT: 80
      APP_URL: http://$APP_PUBLIC_FQDN
      DB_ENGINE: ${DB_ENGINE}
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: http://$APP_PUBLIC_FQDN/api/auth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    ports:
      - 80:80
    volumes:
      - uploaded-files-data:/data/files

  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  uploaded-files-data:
  postgres-data: